# Generated by Django 5.0.2 on 2024-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userprofile_photo_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, through='main.Subscription', to='main.course'),
        ),
    ]
